### PR TITLE
chore(deps): bumps deps

### PR DESCRIPTION
**Pull request by capaj**

### CODE REVIEW

**Comment by simoneb** [comment]
@capaj let's let dependabot take care of dependencies

**Comment by capaj** [comment]
@simoneb I bumped it because when you are using mercurius>=7 you get npm error trying to install this.

Dependabot does not bump majors or it does?

**Comment by simoneb** [comment]
There is a different problem here. Dependabot [doesn't update peerDepencencies](https://github.com/dependabot/dependabot-core/issues/1242). Mercurius is a peer dependency here. We should basically expand the range of the versions of mercurius we support. We still have a potential problem though, we're not testing any of those integrations. I wonder if we should remove the peerDependency in the first place in fact, so we don't have versioning issues. Fastify has its dependency mechanism already so I'm not sure we need to do it ourselves.

**Comment by simoneb** [comment]
I suggest we do this:

- remove the peerdependency on mercurius
- use fastify plugin dependencies (which we may already be using) to define a dependency on mercurius

**Comment by simoneb** [comment]
On the second point, we're already good https://github.com/nearform/mercurius-apollo-registry/blob/master/index.js#L168

**Pull request closed without merging**
